### ISSUE TITLE
Wrong parsing of Polish chars

### ISSUE THREAD

**Issue by marcingol1** [tomblachut/AGH-schedule-optimizer#1]
Polish chars are parsed improperly

- [ Parse polish chars or replace them ]

![screen shot 2017-03-05 at 21 06 50](https://cloud.githubusercontent.com/assets/8483122/23590870/180a33be-01e8-11e7-8aee-9e408c4f4d93.png)

**Comment by tomblachut** [comment]
Strange, works for me every time throughout semesters...

Are you on Windows like me by any chance?

![image](https://cloud.githubusercontent.com/assets/615013/23591239/9eca4a2e-01ed-11e7-9489-552fc205a38a.png)

**Comment by marcingol1** [comment]
Hmm, nope MacOs Sierra. Might be the problem of shelljs parsing some ASCII or some other weird inconsitency between OS's. Script run through bash (zsh to be precise)

**Comment by tomblachut** [comment]
Unfortunately I have no idea how to fix this

**Comment by marcingol1** [comment]
Kk, closing issue- wanted to notify that it didn't helped me with schedule :octocat:
